/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import tdt4250.ra.rax1.Department
import org.eclipse.emf.ecore.util.EcoreUtil

@RunWith(XtextRunner)
@InjectWith(Rax1InjectorProvider)
class Rax1ParsingTest {
	@Inject
	ParseHelper<Department> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			IDI - "Dept. of CS"
			
			Persons:
				"Hallvard Trætteberg"
				Adrian
			
			Courses:
				TDT4250 - "Advanced Software Design": "Hallvard Trætteberg" 100%
				IT1901 - InfProj: Adrian 70%, "Hallvard Trætteberg" 30%

		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
		// the <=> 'spaceship' operator is mapped to Assert.assertEquals
		// when defining the operator_spaceship method below
		2 <=> result.persons.size()
		val hallvard = result.persons.get(0);
		val adrian = result.persons.get(1);
		2 <=> result.courses.size()
		val tdt4250 = result.courses.get(0);
		val it1901 = result.courses.get(1);
		1 <=> tdt4250.allocations.size()
		hallvard <=> tdt4250.allocations.get(0).person
		100 <=> tdt4250.allocations.get(0).percentage		
		2 <=> it1901.allocations.size()
		adrian <=> it1901.allocations.get(0).person
		70 <=> it1901.allocations.get(0).percentage		
		hallvard <=> it1901.allocations.get(1).person
		30 <=> it1901.allocations.get(1).percentage		
	}
	
	// maps the <=> 'spaceship' operator to Assert.assertEquals
	private def void operator_spaceship(Object expected, Object actual) {
		Assert.assertEquals(expected, actual);
	}
}
