/*
 * generated by Xtext 2.18.0.M3
 */
grammar InternalRax2;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package tdt4250.ra.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package tdt4250.ra.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import tdt4250.ra.services.Rax2GrammarAccess;

}
@parser::members {
	private Rax2GrammarAccess grammarAccess;

	public void setGrammarAccess(Rax2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleDepartment
entryRuleDepartment
:
{ before(grammarAccess.getDepartmentRule()); }
	 ruleDepartment
{ after(grammarAccess.getDepartmentRule()); } 
	 EOF 
;

// Rule Department
ruleDepartment 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getDepartmentAccess().getGroup()); }
		(rule__Department__Group__0)
		{ after(grammarAccess.getDepartmentAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleNameOrString
entryRuleNameOrString
:
{ before(grammarAccess.getNameOrStringRule()); }
	 ruleNameOrString
{ after(grammarAccess.getNameOrStringRule()); } 
	 EOF 
;

// Rule NameOrString
ruleNameOrString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getNameOrStringAccess().getAlternatives()); }
		(rule__NameOrString__Alternatives)
		{ after(grammarAccess.getNameOrStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePerson
entryRulePerson
:
{ before(grammarAccess.getPersonRule()); }
	 rulePerson
{ after(grammarAccess.getPersonRule()); } 
	 EOF 
;

// Rule Person
rulePerson 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPersonAccess().getNameAssignment()); }
		(rule__Person__NameAssignment)
		{ after(grammarAccess.getPersonAccess().getNameAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCourse
entryRuleCourse
:
{ before(grammarAccess.getCourseRule()); }
	 ruleCourse
{ after(grammarAccess.getCourseRule()); } 
	 EOF 
;

// Rule Course
ruleCourse 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCourseAccess().getGroup()); }
		(rule__Course__Group__0)
		{ after(grammarAccess.getCourseAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleRole
entryRuleRole
:
{ before(grammarAccess.getRoleRule()); }
	 ruleRole
{ after(grammarAccess.getRoleRule()); } 
	 EOF 
;

// Rule Role
ruleRole 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getRoleAccess().getGroup()); }
		(rule__Role__Group__0)
		{ after(grammarAccess.getRoleAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleFactorAsPercentage
entryRuleFactorAsPercentage
:
{ before(grammarAccess.getFactorAsPercentageRule()); }
	 ruleFactorAsPercentage
{ after(grammarAccess.getFactorAsPercentageRule()); } 
	 EOF 
;

// Rule FactorAsPercentage
ruleFactorAsPercentage 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getFactorAsPercentageAccess().getGroup()); }
		(rule__FactorAsPercentage__Group__0)
		{ after(grammarAccess.getFactorAsPercentageAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleResourceAllocation
entryRuleResourceAllocation
:
{ before(grammarAccess.getResourceAllocationRule()); }
	 ruleResourceAllocation
{ after(grammarAccess.getResourceAllocationRule()); } 
	 EOF 
;

// Rule ResourceAllocation
ruleResourceAllocation 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getGroup()); }
		(rule__ResourceAllocation__Group__0)
		{ after(grammarAccess.getResourceAllocationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__NameOrString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNameOrStringAccess().getIDTerminalRuleCall_0()); }
		RULE_ID
		{ after(grammarAccess.getNameOrStringAccess().getIDTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getNameOrStringAccess().getSTRINGTerminalRuleCall_1()); }
		RULE_STRING
		{ after(grammarAccess.getNameOrStringAccess().getSTRINGTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Alternatives_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getGroup_2_0()); }
		(rule__ResourceAllocation__Group_2_0__0)
		{ after(grammarAccess.getResourceAllocationAccess().getGroup_2_0()); }
	)
	|
	(
		{ before(grammarAccess.getResourceAllocationAccess().getGroup_2_1()); }
		(rule__ResourceAllocation__Group_2_1__0)
		{ after(grammarAccess.getResourceAllocationAccess().getGroup_2_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__0__Impl
	rule__Department__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getShortNameAssignment_0()); }
	(rule__Department__ShortNameAssignment_0)
	{ after(grammarAccess.getDepartmentAccess().getShortNameAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__1__Impl
	rule__Department__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getHyphenMinusKeyword_1()); }
	'-'
	{ after(grammarAccess.getDepartmentAccess().getHyphenMinusKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__2__Impl
	rule__Department__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getNameAssignment_2()); }
	(rule__Department__NameAssignment_2)
	{ after(grammarAccess.getDepartmentAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__3__Impl
	rule__Department__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getPersonsKeyword_3()); }
	'Persons:'
	{ after(grammarAccess.getDepartmentAccess().getPersonsKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__4__Impl
	rule__Department__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getStaffAssignment_4()); }
	(rule__Department__StaffAssignment_4)*
	{ after(grammarAccess.getDepartmentAccess().getStaffAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__5__Impl
	rule__Department__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getCoursesKeyword_5()); }
	'Courses:'
	{ after(grammarAccess.getDepartmentAccess().getCoursesKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__6__Impl
	rule__Department__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getCoursesAssignment_6()); }
	(rule__Department__CoursesAssignment_6)*
	{ after(grammarAccess.getDepartmentAccess().getCoursesAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__7__Impl
	rule__Department__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getAllocationsKeyword_7()); }
	'Allocations:'
	{ after(grammarAccess.getDepartmentAccess().getAllocationsKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__8__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getResourceAllocationsAssignment_8()); }
	(rule__Department__ResourceAllocationsAssignment_8)*
	{ after(grammarAccess.getDepartmentAccess().getResourceAllocationsAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Course__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__0__Impl
	rule__Course__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getCodeAssignment_0()); }
	(rule__Course__CodeAssignment_0)
	{ after(grammarAccess.getCourseAccess().getCodeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__1__Impl
	rule__Course__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getHyphenMinusKeyword_1()); }
	'-'
	{ after(grammarAccess.getCourseAccess().getHyphenMinusKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__2__Impl
	rule__Course__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getNameAssignment_2()); }
	(rule__Course__NameAssignment_2)
	{ after(grammarAccess.getCourseAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getGroup_3()); }
	(rule__Course__Group_3__0)?
	{ after(grammarAccess.getCourseAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Course__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_3__0__Impl
	rule__Course__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getRequiresKeyword_3_0()); }
	'requires'
	{ after(grammarAccess.getCourseAccess().getRequiresKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_3__1__Impl
	rule__Course__Group_3__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getRolesAssignment_3_1()); }
	(rule__Course__RolesAssignment_3_1)
	{ after(grammarAccess.getCourseAccess().getRolesAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_3__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getGroup_3_2()); }
	(rule__Course__Group_3_2__0)*
	{ after(grammarAccess.getCourseAccess().getGroup_3_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Course__Group_3_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_3_2__0__Impl
	rule__Course__Group_3_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getCommaKeyword_3_2_0()); }
	','
	{ after(grammarAccess.getCourseAccess().getCommaKeyword_3_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_3_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_3_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getRolesAssignment_3_2_1()); }
	(rule__Course__RolesAssignment_3_2_1)
	{ after(grammarAccess.getCourseAccess().getRolesAssignment_3_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Role__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Role__Group__0__Impl
	rule__Role__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoleAccess().getNameAssignment_0()); }
	(rule__Role__NameAssignment_0)
	{ after(grammarAccess.getRoleAccess().getNameAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Role__Group__1__Impl
	rule__Role__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoleAccess().getForKeyword_1()); }
	'for'
	{ after(grammarAccess.getRoleAccess().getForKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Role__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoleAccess().getWorkloadAssignment_2()); }
	(rule__Role__WorkloadAssignment_2)
	{ after(grammarAccess.getRoleAccess().getWorkloadAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__FactorAsPercentage__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__FactorAsPercentage__Group__0__Impl
	rule__FactorAsPercentage__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFactorAsPercentageAccess().getINTTerminalRuleCall_0()); }
	RULE_INT
	{ after(grammarAccess.getFactorAsPercentageAccess().getINTTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__FactorAsPercentage__Group__1__Impl
	rule__FactorAsPercentage__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFactorAsPercentageAccess().getGroup_1()); }
	(rule__FactorAsPercentage__Group_1__0)?
	{ after(grammarAccess.getFactorAsPercentageAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__FactorAsPercentage__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFactorAsPercentageAccess().getPercentSignKeyword_2()); }
	'%'
	{ after(grammarAccess.getFactorAsPercentageAccess().getPercentSignKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__FactorAsPercentage__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__FactorAsPercentage__Group_1__0__Impl
	rule__FactorAsPercentage__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFactorAsPercentageAccess().getFullStopKeyword_1_0()); }
	'.'
	{ after(grammarAccess.getFactorAsPercentageAccess().getFullStopKeyword_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__FactorAsPercentage__Group_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__FactorAsPercentage__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFactorAsPercentageAccess().getINTTerminalRuleCall_1_1()); }
	RULE_INT
	{ after(grammarAccess.getFactorAsPercentageAccess().getINTTerminalRuleCall_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ResourceAllocation__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group__0__Impl
	rule__ResourceAllocation__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getPersonAssignment_0()); }
	(rule__ResourceAllocation__PersonAssignment_0)
	{ after(grammarAccess.getResourceAllocationAccess().getPersonAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group__1__Impl
	rule__ResourceAllocation__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getIsKeyword_1()); }
	'is'
	{ after(grammarAccess.getResourceAllocationAccess().getIsKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getAlternatives_2()); }
	(rule__ResourceAllocation__Alternatives_2)
	{ after(grammarAccess.getResourceAllocationAccess().getAlternatives_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ResourceAllocation__Group_2_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_0__0__Impl
	rule__ResourceAllocation__Group_2_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getFactorAssignment_2_0_0()); }
	(rule__ResourceAllocation__FactorAssignment_2_0_0)
	{ after(grammarAccess.getResourceAllocationAccess().getFactorAssignment_2_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_0__1__Impl
	rule__ResourceAllocation__Group_2_0__2
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getInKeyword_2_0_1()); }
	'in'
	{ after(grammarAccess.getResourceAllocationAccess().getInKeyword_2_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_0__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_0__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_0__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getCourseAssignment_2_0_2()); }
	(rule__ResourceAllocation__CourseAssignment_2_0_2)
	{ after(grammarAccess.getResourceAllocationAccess().getCourseAssignment_2_0_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ResourceAllocation__Group_2_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_1__0__Impl
	rule__ResourceAllocation__Group_2_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getInKeyword_2_1_0()); }
	'in'
	{ after(grammarAccess.getResourceAllocationAccess().getInKeyword_2_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_1__1__Impl
	rule__ResourceAllocation__Group_2_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getCourseAssignment_2_1_1()); }
	(rule__ResourceAllocation__CourseAssignment_2_1_1)
	{ after(grammarAccess.getResourceAllocationAccess().getCourseAssignment_2_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_1__2__Impl
	rule__ResourceAllocation__Group_2_1__3
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getAsKeyword_2_1_2()); }
	'as'
	{ after(grammarAccess.getResourceAllocationAccess().getAsKeyword_2_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_1__3__Impl
	rule__ResourceAllocation__Group_2_1__4
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getFactorAssignment_2_1_3()); }
	(rule__ResourceAllocation__FactorAssignment_2_1_3)
	{ after(grammarAccess.getResourceAllocationAccess().getFactorAssignment_2_1_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group_2_1__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group_2_1__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getRoleAssignment_2_1_4()); }
	(rule__ResourceAllocation__RoleAssignment_2_1_4)
	{ after(grammarAccess.getResourceAllocationAccess().getRoleAssignment_2_1_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Department__ShortNameAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getShortNameIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getDepartmentAccess().getShortNameIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getNameSTRINGTerminalRuleCall_2_0()); }
		RULE_STRING
		{ after(grammarAccess.getDepartmentAccess().getNameSTRINGTerminalRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__StaffAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getStaffPersonParserRuleCall_4_0()); }
		rulePerson
		{ after(grammarAccess.getDepartmentAccess().getStaffPersonParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__CoursesAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getCoursesCourseParserRuleCall_6_0()); }
		ruleCourse
		{ after(grammarAccess.getDepartmentAccess().getCoursesCourseParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__ResourceAllocationsAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getResourceAllocationsResourceAllocationParserRuleCall_8_0()); }
		ruleResourceAllocation
		{ after(grammarAccess.getDepartmentAccess().getResourceAllocationsResourceAllocationParserRuleCall_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__NameAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getNameNameOrStringParserRuleCall_0()); }
		ruleNameOrString
		{ after(grammarAccess.getPersonAccess().getNameNameOrStringParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__CodeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getCodeIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getCourseAccess().getCodeIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getNameNameOrStringParserRuleCall_2_0()); }
		ruleNameOrString
		{ after(grammarAccess.getCourseAccess().getNameNameOrStringParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__RolesAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getRolesRoleParserRuleCall_3_1_0()); }
		ruleRole
		{ after(grammarAccess.getCourseAccess().getRolesRoleParserRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__RolesAssignment_3_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getRolesRoleParserRuleCall_3_2_1_0()); }
		ruleRole
		{ after(grammarAccess.getCourseAccess().getRolesRoleParserRuleCall_3_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__NameAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoleAccess().getNameIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getRoleAccess().getNameIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__WorkloadAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoleAccess().getWorkloadFactorAsPercentageParserRuleCall_2_0()); }
		ruleFactorAsPercentage
		{ after(grammarAccess.getRoleAccess().getWorkloadFactorAsPercentageParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__PersonAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getPersonPersonCrossReference_0_0()); }
		(
			{ before(grammarAccess.getResourceAllocationAccess().getPersonPersonNameOrStringParserRuleCall_0_0_1()); }
			ruleNameOrString
			{ after(grammarAccess.getResourceAllocationAccess().getPersonPersonNameOrStringParserRuleCall_0_0_1()); }
		)
		{ after(grammarAccess.getResourceAllocationAccess().getPersonPersonCrossReference_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__FactorAssignment_2_0_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getFactorFactorAsPercentageParserRuleCall_2_0_0_0()); }
		ruleFactorAsPercentage
		{ after(grammarAccess.getResourceAllocationAccess().getFactorFactorAsPercentageParserRuleCall_2_0_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__CourseAssignment_2_0_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getCourseCourseCrossReference_2_0_2_0()); }
		(
			{ before(grammarAccess.getResourceAllocationAccess().getCourseCourseIDTerminalRuleCall_2_0_2_0_1()); }
			RULE_ID
			{ after(grammarAccess.getResourceAllocationAccess().getCourseCourseIDTerminalRuleCall_2_0_2_0_1()); }
		)
		{ after(grammarAccess.getResourceAllocationAccess().getCourseCourseCrossReference_2_0_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__CourseAssignment_2_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getCourseCourseCrossReference_2_1_1_0()); }
		(
			{ before(grammarAccess.getResourceAllocationAccess().getCourseCourseIDTerminalRuleCall_2_1_1_0_1()); }
			RULE_ID
			{ after(grammarAccess.getResourceAllocationAccess().getCourseCourseIDTerminalRuleCall_2_1_1_0_1()); }
		)
		{ after(grammarAccess.getResourceAllocationAccess().getCourseCourseCrossReference_2_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__FactorAssignment_2_1_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getFactorFactorAsPercentageParserRuleCall_2_1_3_0()); }
		ruleFactorAsPercentage
		{ after(grammarAccess.getResourceAllocationAccess().getFactorFactorAsPercentageParserRuleCall_2_1_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__RoleAssignment_2_1_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getRoleRoleCrossReference_2_1_4_0()); }
		(
			{ before(grammarAccess.getResourceAllocationAccess().getRoleRoleIDTerminalRuleCall_2_1_4_0_1()); }
			RULE_ID
			{ after(grammarAccess.getResourceAllocationAccess().getRoleRoleIDTerminalRuleCall_2_1_4_0_1()); }
		)
		{ after(grammarAccess.getResourceAllocationAccess().getRoleRoleCrossReference_2_1_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
