# Generated by Django 3.0.2 on 2020-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email address"),
        ),
    ]
