/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class Rax1ScopeProvider extends AbstractRax1ScopeProvider {

}
