/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import tdt4250.ra.Rax2RuntimeModule
import tdt4250.ra.Rax2StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Rax2IdeSetup extends Rax2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Rax2RuntimeModule, new Rax2IdeModule))
	}
	
}
