/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.validation

import org.eclipse.xtext.validation.Check
import tdt4250.ra.rax1.Person
import tdt4250.ra.rax1.Rax1Package

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class Rax1Validator extends AbstractRax1Validator {
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkPersonName(Person person) {
		val name = person.name
		for (var i = 0; i < name.length; i++) {
			if (! Character.isLetter(name.charAt(i))) {
				warning('Name should start with a capital', 
						Rax1Package.Literals.PERSON__NAME,
						INVALID_NAME)
				
			}
		}
	}
	
}
