/*
 * generated by Xtext 2.27.0
 */
grammar InternalRax1;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package tdt4250.ra.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package tdt4250.ra.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import tdt4250.ra.services.Rax1GrammarAccess;

}

@parser::members {

 	private Rax1GrammarAccess grammarAccess;

    public InternalRax1Parser(TokenStream input, Rax1GrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Department";
   	}

   	@Override
   	protected Rax1GrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleDepartment
entryRuleDepartment returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDepartmentRule()); }
	iv_ruleDepartment=ruleDepartment
	{ $current=$iv_ruleDepartment.current; }
	EOF;

// Rule Department
ruleDepartment returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_shortName_0_0=RULE_ID
				{
					newLeafNode(lv_shortName_0_0, grammarAccess.getDepartmentAccess().getShortNameIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDepartmentRule());
					}
					setWithLastConsumed(
						$current,
						"shortName",
						lv_shortName_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_1='-'
		{
			newLeafNode(otherlv_1, grammarAccess.getDepartmentAccess().getHyphenMinusKeyword_1());
		}
		(
			(
				lv_name_2_0=RULE_STRING
				{
					newLeafNode(lv_name_2_0, grammarAccess.getDepartmentAccess().getNameSTRINGTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDepartmentRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_2_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_3='Persons:'
		{
			newLeafNode(otherlv_3, grammarAccess.getDepartmentAccess().getPersonsKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDepartmentAccess().getPersonsPersonParserRuleCall_4_0());
				}
				lv_persons_4_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDepartmentRule());
					}
					add(
						$current,
						"persons",
						lv_persons_4_0,
						"tdt4250.ra.Rax1.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_5='Courses:'
		{
			newLeafNode(otherlv_5, grammarAccess.getDepartmentAccess().getCoursesKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDepartmentAccess().getCoursesCourseParserRuleCall_6_0());
				}
				lv_courses_6_0=ruleCourse
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDepartmentRule());
					}
					add(
						$current,
						"courses",
						lv_courses_6_0,
						"tdt4250.ra.Rax1.Course");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRuleNameOrString
entryRuleNameOrString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getNameOrStringRule()); }
	iv_ruleNameOrString=ruleNameOrString
	{ $current=$iv_ruleNameOrString.current.getText(); }
	EOF;

// Rule NameOrString
ruleNameOrString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getNameOrStringAccess().getIDTerminalRuleCall_0());
		}
		    |
		this_STRING_1=RULE_STRING
		{
			$current.merge(this_STRING_1);
		}
		{
			newLeafNode(this_STRING_1, grammarAccess.getNameOrStringAccess().getSTRINGTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRulePerson
entryRulePerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonRule()); }
	iv_rulePerson=rulePerson
	{ $current=$iv_rulePerson.current; }
	EOF;

// Rule Person
rulePerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getPersonAccess().getNameNameOrStringParserRuleCall_0());
			}
			lv_name_0_0=ruleNameOrString
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getPersonRule());
				}
				set(
					$current,
					"name",
					lv_name_0_0,
					"tdt4250.ra.Rax1.NameOrString");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleCourse
entryRuleCourse returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCourseRule()); }
	iv_ruleCourse=ruleCourse
	{ $current=$iv_ruleCourse.current; }
	EOF;

// Rule Course
ruleCourse returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_code_0_0=RULE_ID
				{
					newLeafNode(lv_code_0_0, grammarAccess.getCourseAccess().getCodeIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCourseRule());
					}
					setWithLastConsumed(
						$current,
						"code",
						lv_code_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_1='-'
		{
			newLeafNode(otherlv_1, grammarAccess.getCourseAccess().getHyphenMinusKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getCourseAccess().getNameNameOrStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleNameOrString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCourseRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"tdt4250.ra.Rax1.NameOrString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3=':'
		{
			newLeafNode(otherlv_3, grammarAccess.getCourseAccess().getColonKeyword_3());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getCourseAccess().getAllocationsResourceAllocationParserRuleCall_4_0_0());
					}
					lv_allocations_4_0=ruleResourceAllocation
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getCourseRule());
						}
						add(
							$current,
							"allocations",
							lv_allocations_4_0,
							"tdt4250.ra.Rax1.ResourceAllocation");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_5=','
				{
					newLeafNode(otherlv_5, grammarAccess.getCourseAccess().getCommaKeyword_4_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getCourseAccess().getAllocationsResourceAllocationParserRuleCall_4_1_1_0());
						}
						lv_allocations_6_0=ruleResourceAllocation
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getCourseRule());
							}
							add(
								$current,
								"allocations",
								lv_allocations_6_0,
								"tdt4250.ra.Rax1.ResourceAllocation");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
	)
;

// Entry rule entryRuleResourceAllocation
entryRuleResourceAllocation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getResourceAllocationRule()); }
	iv_ruleResourceAllocation=ruleResourceAllocation
	{ $current=$iv_ruleResourceAllocation.current; }
	EOF;

// Rule ResourceAllocation
ruleResourceAllocation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getResourceAllocationRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getResourceAllocationAccess().getPersonPersonCrossReference_0_0());
				}
				ruleNameOrString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				lv_percentage_1_0=RULE_INT
				{
					newLeafNode(lv_percentage_1_0, grammarAccess.getResourceAllocationAccess().getPercentageINTTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getResourceAllocationRule());
					}
					setWithLastConsumed(
						$current,
						"percentage",
						lv_percentage_1_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_2='%'
		{
			newLeafNode(otherlv_2, grammarAccess.getResourceAllocationAccess().getPercentSignKeyword_2());
		}
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
