/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import tdt4250.ra.Course
import tdt4250.ra.Department
import tdt4250.ra.services.Rax2GrammarAccess

class Rax2Formatter extends AbstractFormatter2 {
	
	@Inject extension Rax2GrammarAccess

	def dispatch void format(Department department, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (person : department.staff) {
			person.format
		}
		for (course : department.courses) {
			course.format
		}
		for (resourceAllocation : department.resourceAllocations) {
			resourceAllocation.format
		}
	}

	def dispatch void format(Course course, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (role : course.roles) {
			role.format
		}
	}
	
	// TODO: implement for 
}
