/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import tdt4250.ra.Rax1RuntimeModule
import tdt4250.ra.Rax1StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Rax1IdeSetup extends Rax1StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Rax1RuntimeModule, new Rax1IdeModule))
	}
	
}
