/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.scoping

import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.scoping.IScope
import tdt4250.ra.RaPackage
import tdt4250.ra.ResourceAllocation
import org.eclipse.xtext.scoping.Scopes
import tdt4250.ra.Role
import tdt4250.ra.Department

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class Rax2ScopeProvider extends AbstractRax2ScopeProvider {

	override IScope getScope(EObject context, EReference ref) {
		if (context instanceof ResourceAllocation && ref == RaPackage.eINSTANCE.resourceAllocation_Role) {
			val course = (context as ResourceAllocation).course
			if (course !== null) {
				Scopes.scopeFor(course.roles)
			} else {
				val allRoles = <Role>newArrayList
				val dep = (context.eContainer() as Department)
				dep.courses.forEach[allRoles += roles]
				Scopes.scopeFor(allRoles)				
			}
		} else {
			super.getScope(context, ref)
		}
	}
}
