/*
 * generated by Xtext 2.27.0
 */
grammar InternalRax1;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package tdt4250.ra.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package tdt4250.ra.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import tdt4250.ra.services.Rax1GrammarAccess;

}
@parser::members {
	private Rax1GrammarAccess grammarAccess;

	public void setGrammarAccess(Rax1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleDepartment
entryRuleDepartment
:
{ before(grammarAccess.getDepartmentRule()); }
	 ruleDepartment
{ after(grammarAccess.getDepartmentRule()); } 
	 EOF 
;

// Rule Department
ruleDepartment 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getDepartmentAccess().getGroup()); }
		(rule__Department__Group__0)
		{ after(grammarAccess.getDepartmentAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleNameOrString
entryRuleNameOrString
:
{ before(grammarAccess.getNameOrStringRule()); }
	 ruleNameOrString
{ after(grammarAccess.getNameOrStringRule()); } 
	 EOF 
;

// Rule NameOrString
ruleNameOrString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getNameOrStringAccess().getAlternatives()); }
		(rule__NameOrString__Alternatives)
		{ after(grammarAccess.getNameOrStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePerson
entryRulePerson
:
{ before(grammarAccess.getPersonRule()); }
	 rulePerson
{ after(grammarAccess.getPersonRule()); } 
	 EOF 
;

// Rule Person
rulePerson 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPersonAccess().getNameAssignment()); }
		(rule__Person__NameAssignment)
		{ after(grammarAccess.getPersonAccess().getNameAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleCourse
entryRuleCourse
:
{ before(grammarAccess.getCourseRule()); }
	 ruleCourse
{ after(grammarAccess.getCourseRule()); } 
	 EOF 
;

// Rule Course
ruleCourse 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getCourseAccess().getGroup()); }
		(rule__Course__Group__0)
		{ after(grammarAccess.getCourseAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleResourceAllocation
entryRuleResourceAllocation
:
{ before(grammarAccess.getResourceAllocationRule()); }
	 ruleResourceAllocation
{ after(grammarAccess.getResourceAllocationRule()); } 
	 EOF 
;

// Rule ResourceAllocation
ruleResourceAllocation 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getGroup()); }
		(rule__ResourceAllocation__Group__0)
		{ after(grammarAccess.getResourceAllocationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__NameOrString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNameOrStringAccess().getIDTerminalRuleCall_0()); }
		RULE_ID
		{ after(grammarAccess.getNameOrStringAccess().getIDTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getNameOrStringAccess().getSTRINGTerminalRuleCall_1()); }
		RULE_STRING
		{ after(grammarAccess.getNameOrStringAccess().getSTRINGTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__0__Impl
	rule__Department__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getShortNameAssignment_0()); }
	(rule__Department__ShortNameAssignment_0)
	{ after(grammarAccess.getDepartmentAccess().getShortNameAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__1__Impl
	rule__Department__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getHyphenMinusKeyword_1()); }
	'-'
	{ after(grammarAccess.getDepartmentAccess().getHyphenMinusKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__2__Impl
	rule__Department__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getNameAssignment_2()); }
	(rule__Department__NameAssignment_2)
	{ after(grammarAccess.getDepartmentAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__3__Impl
	rule__Department__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getPersonsKeyword_3()); }
	'Persons:'
	{ after(grammarAccess.getDepartmentAccess().getPersonsKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__4__Impl
	rule__Department__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getPersonsAssignment_4()); }
	(rule__Department__PersonsAssignment_4)*
	{ after(grammarAccess.getDepartmentAccess().getPersonsAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__5__Impl
	rule__Department__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getCoursesKeyword_5()); }
	'Courses:'
	{ after(grammarAccess.getDepartmentAccess().getCoursesKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Department__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDepartmentAccess().getCoursesAssignment_6()); }
	(rule__Department__CoursesAssignment_6)*
	{ after(grammarAccess.getDepartmentAccess().getCoursesAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Course__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__0__Impl
	rule__Course__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getCodeAssignment_0()); }
	(rule__Course__CodeAssignment_0)
	{ after(grammarAccess.getCourseAccess().getCodeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__1__Impl
	rule__Course__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getHyphenMinusKeyword_1()); }
	'-'
	{ after(grammarAccess.getCourseAccess().getHyphenMinusKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__2__Impl
	rule__Course__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getNameAssignment_2()); }
	(rule__Course__NameAssignment_2)
	{ after(grammarAccess.getCourseAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__3__Impl
	rule__Course__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getColonKeyword_3()); }
	':'
	{ after(grammarAccess.getCourseAccess().getColonKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getGroup_4()); }
	(rule__Course__Group_4__0)?
	{ after(grammarAccess.getCourseAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Course__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_4__0__Impl
	rule__Course__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getAllocationsAssignment_4_0()); }
	(rule__Course__AllocationsAssignment_4_0)
	{ after(grammarAccess.getCourseAccess().getAllocationsAssignment_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getGroup_4_1()); }
	(rule__Course__Group_4_1__0)*
	{ after(grammarAccess.getCourseAccess().getGroup_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Course__Group_4_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_4_1__0__Impl
	rule__Course__Group_4_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_4_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getCommaKeyword_4_1_0()); }
	','
	{ after(grammarAccess.getCourseAccess().getCommaKeyword_4_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_4_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Course__Group_4_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__Group_4_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getCourseAccess().getAllocationsAssignment_4_1_1()); }
	(rule__Course__AllocationsAssignment_4_1_1)
	{ after(grammarAccess.getCourseAccess().getAllocationsAssignment_4_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ResourceAllocation__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group__0__Impl
	rule__ResourceAllocation__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getPersonAssignment_0()); }
	(rule__ResourceAllocation__PersonAssignment_0)
	{ after(grammarAccess.getResourceAllocationAccess().getPersonAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group__1__Impl
	rule__ResourceAllocation__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getPercentageAssignment_1()); }
	(rule__ResourceAllocation__PercentageAssignment_1)
	{ after(grammarAccess.getResourceAllocationAccess().getPercentageAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ResourceAllocation__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getResourceAllocationAccess().getPercentSignKeyword_2()); }
	'%'
	{ after(grammarAccess.getResourceAllocationAccess().getPercentSignKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Department__ShortNameAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getShortNameIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getDepartmentAccess().getShortNameIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getNameSTRINGTerminalRuleCall_2_0()); }
		RULE_STRING
		{ after(grammarAccess.getDepartmentAccess().getNameSTRINGTerminalRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__PersonsAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getPersonsPersonParserRuleCall_4_0()); }
		rulePerson
		{ after(grammarAccess.getDepartmentAccess().getPersonsPersonParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Department__CoursesAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDepartmentAccess().getCoursesCourseParserRuleCall_6_0()); }
		ruleCourse
		{ after(grammarAccess.getDepartmentAccess().getCoursesCourseParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__NameAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getNameNameOrStringParserRuleCall_0()); }
		ruleNameOrString
		{ after(grammarAccess.getPersonAccess().getNameNameOrStringParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__CodeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getCodeIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getCourseAccess().getCodeIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getNameNameOrStringParserRuleCall_2_0()); }
		ruleNameOrString
		{ after(grammarAccess.getCourseAccess().getNameNameOrStringParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__AllocationsAssignment_4_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getAllocationsResourceAllocationParserRuleCall_4_0_0()); }
		ruleResourceAllocation
		{ after(grammarAccess.getCourseAccess().getAllocationsResourceAllocationParserRuleCall_4_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Course__AllocationsAssignment_4_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getCourseAccess().getAllocationsResourceAllocationParserRuleCall_4_1_1_0()); }
		ruleResourceAllocation
		{ after(grammarAccess.getCourseAccess().getAllocationsResourceAllocationParserRuleCall_4_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__PersonAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getPersonPersonCrossReference_0_0()); }
		(
			{ before(grammarAccess.getResourceAllocationAccess().getPersonPersonNameOrStringParserRuleCall_0_0_1()); }
			ruleNameOrString
			{ after(grammarAccess.getResourceAllocationAccess().getPersonPersonNameOrStringParserRuleCall_0_0_1()); }
		)
		{ after(grammarAccess.getResourceAllocationAccess().getPersonPersonCrossReference_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ResourceAllocation__PercentageAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getResourceAllocationAccess().getPercentageINTTerminalRuleCall_1_0()); }
		RULE_INT
		{ after(grammarAccess.getResourceAllocationAccess().getPercentageINTTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
