/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import tdt4250.ra.xtext2.ui.internal.Xtext2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Rax2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Xtext2Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Xtext2Activator activator = Xtext2Activator.getInstance();
		return activator != null ? activator.getInjector(Xtext2Activator.TDT4250_RA_RAX2) : null;
	}

}
