/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Rax1StandaloneSetup extends Rax1StandaloneSetupGenerated {

	def static void doSetup() {
		new Rax1StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
