/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class Rax2GrammarAccess extends AbstractGrammarElementFinder {
	
	public class DepartmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.ra.Rax2.Department");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cShortNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cShortNameIDTerminalRuleCall_0_0 = (RuleCall)cShortNameAssignment_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cPersonsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStaffAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStaffPersonParserRuleCall_4_0 = (RuleCall)cStaffAssignment_4.eContents().get(0);
		private final Keyword cCoursesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCoursesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCoursesCourseParserRuleCall_6_0 = (RuleCall)cCoursesAssignment_6.eContents().get(0);
		private final Keyword cAllocationsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cResourceAllocationsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cResourceAllocationsResourceAllocationParserRuleCall_8_0 = (RuleCall)cResourceAllocationsAssignment_8.eContents().get(0);
		
		//Department:
		//	shortName=ID '-' name=STRING
		//	'Persons:'
		//	staff+=Person*
		//	'Courses:'
		//	courses+=Course*
		//	'Allocations:'
		//	resourceAllocations+=ResourceAllocation*;
		@Override public ParserRule getRule() { return rule; }
		
		//shortName=ID '-' name=STRING 'Persons:' staff+=Person* 'Courses:' courses+=Course* 'Allocations:'
		//resourceAllocations+=ResourceAllocation*
		public Group getGroup() { return cGroup; }
		
		//shortName=ID
		public Assignment getShortNameAssignment_0() { return cShortNameAssignment_0; }
		
		//ID
		public RuleCall getShortNameIDTerminalRuleCall_0_0() { return cShortNameIDTerminalRuleCall_0_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//'Persons:'
		public Keyword getPersonsKeyword_3() { return cPersonsKeyword_3; }
		
		//staff+=Person*
		public Assignment getStaffAssignment_4() { return cStaffAssignment_4; }
		
		//Person
		public RuleCall getStaffPersonParserRuleCall_4_0() { return cStaffPersonParserRuleCall_4_0; }
		
		//'Courses:'
		public Keyword getCoursesKeyword_5() { return cCoursesKeyword_5; }
		
		//courses+=Course*
		public Assignment getCoursesAssignment_6() { return cCoursesAssignment_6; }
		
		//Course
		public RuleCall getCoursesCourseParserRuleCall_6_0() { return cCoursesCourseParserRuleCall_6_0; }
		
		//'Allocations:'
		public Keyword getAllocationsKeyword_7() { return cAllocationsKeyword_7; }
		
		//resourceAllocations+=ResourceAllocation*
		public Assignment getResourceAllocationsAssignment_8() { return cResourceAllocationsAssignment_8; }
		
		//ResourceAllocation
		public RuleCall getResourceAllocationsResourceAllocationParserRuleCall_8_0() { return cResourceAllocationsResourceAllocationParserRuleCall_8_0; }
	}
	public class NameOrStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.ra.Rax2.NameOrString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//NameOrString:
		//	ID | STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//ID | STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_1() { return cSTRINGTerminalRuleCall_1; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.ra.Rax2.Person");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameNameOrStringParserRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Person:
		//	name=NameOrString;
		@Override public ParserRule getRule() { return rule; }
		
		//name=NameOrString
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//NameOrString
		public RuleCall getNameNameOrStringParserRuleCall_0() { return cNameNameOrStringParserRuleCall_0; }
	}
	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.ra.Rax2.Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCodeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCodeIDTerminalRuleCall_0_0 = (RuleCall)cCodeAssignment_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNameOrStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRequiresKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRolesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cRolesRoleParserRuleCall_3_1_0 = (RuleCall)cRolesAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cRolesAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cRolesRoleParserRuleCall_3_2_1_0 = (RuleCall)cRolesAssignment_3_2_1.eContents().get(0);
		
		//Course:
		//	code=ID '-' name=NameOrString ('requires' roles+=Role (',' roles+=Role)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//code=ID '-' name=NameOrString ('requires' roles+=Role (',' roles+=Role)*)?
		public Group getGroup() { return cGroup; }
		
		//code=ID
		public Assignment getCodeAssignment_0() { return cCodeAssignment_0; }
		
		//ID
		public RuleCall getCodeIDTerminalRuleCall_0_0() { return cCodeIDTerminalRuleCall_0_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//name=NameOrString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NameOrString
		public RuleCall getNameNameOrStringParserRuleCall_2_0() { return cNameNameOrStringParserRuleCall_2_0; }
		
		//('requires' roles+=Role (',' roles+=Role)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'requires'
		public Keyword getRequiresKeyword_3_0() { return cRequiresKeyword_3_0; }
		
		//roles+=Role
		public Assignment getRolesAssignment_3_1() { return cRolesAssignment_3_1; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_3_1_0() { return cRolesRoleParserRuleCall_3_1_0; }
		
		//(',' roles+=Role)*
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//','
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }
		
		//roles+=Role
		public Assignment getRolesAssignment_3_2_1() { return cRolesAssignment_3_2_1; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_3_2_1_0() { return cRolesRoleParserRuleCall_3_2_1_0; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.ra.Rax2.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cForKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cWorkloadAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cWorkloadFactorAsPercentageParserRuleCall_2_0 = (RuleCall)cWorkloadAssignment_2.eContents().get(0);
		
		//Role:
		//	name=ID 'for' workload=FactorAsPercentage;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID 'for' workload=FactorAsPercentage
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'for'
		public Keyword getForKeyword_1() { return cForKeyword_1; }
		
		//workload=FactorAsPercentage
		public Assignment getWorkloadAssignment_2() { return cWorkloadAssignment_2; }
		
		//FactorAsPercentage
		public RuleCall getWorkloadFactorAsPercentageParserRuleCall_2_0() { return cWorkloadFactorAsPercentageParserRuleCall_2_0; }
	}
	public class FactorAsPercentageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.ra.Rax2.FactorAsPercentage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cPercentSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//FactorAsPercentage ecore::EFloat:
		//	INT ('.' INT)? '%';
		@Override public ParserRule getRule() { return rule; }
		
		//INT ('.' INT)? '%'
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//('.' INT)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_1() { return cINTTerminalRuleCall_1_1; }
		
		//'%'
		public Keyword getPercentSignKeyword_2() { return cPercentSignKeyword_2; }
	}
	public class ResourceAllocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "tdt4250.ra.Rax2.ResourceAllocation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPersonAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPersonPersonCrossReference_0_0 = (CrossReference)cPersonAssignment_0.eContents().get(0);
		private final RuleCall cPersonPersonNameOrStringParserRuleCall_0_0_1 = (RuleCall)cPersonPersonCrossReference_0_0.eContents().get(1);
		private final Keyword cIsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Assignment cFactorAssignment_2_0_0 = (Assignment)cGroup_2_0.eContents().get(0);
		private final RuleCall cFactorFactorAsPercentageParserRuleCall_2_0_0_0 = (RuleCall)cFactorAssignment_2_0_0.eContents().get(0);
		private final Keyword cInKeyword_2_0_1 = (Keyword)cGroup_2_0.eContents().get(1);
		private final Assignment cCourseAssignment_2_0_2 = (Assignment)cGroup_2_0.eContents().get(2);
		private final CrossReference cCourseCourseCrossReference_2_0_2_0 = (CrossReference)cCourseAssignment_2_0_2.eContents().get(0);
		private final RuleCall cCourseCourseIDTerminalRuleCall_2_0_2_0_1 = (RuleCall)cCourseCourseCrossReference_2_0_2_0.eContents().get(1);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cInKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cCourseAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final CrossReference cCourseCourseCrossReference_2_1_1_0 = (CrossReference)cCourseAssignment_2_1_1.eContents().get(0);
		private final RuleCall cCourseCourseIDTerminalRuleCall_2_1_1_0_1 = (RuleCall)cCourseCourseCrossReference_2_1_1_0.eContents().get(1);
		private final Keyword cAsKeyword_2_1_2 = (Keyword)cGroup_2_1.eContents().get(2);
		private final Assignment cFactorAssignment_2_1_3 = (Assignment)cGroup_2_1.eContents().get(3);
		private final RuleCall cFactorFactorAsPercentageParserRuleCall_2_1_3_0 = (RuleCall)cFactorAssignment_2_1_3.eContents().get(0);
		private final Assignment cRoleAssignment_2_1_4 = (Assignment)cGroup_2_1.eContents().get(4);
		private final CrossReference cRoleRoleCrossReference_2_1_4_0 = (CrossReference)cRoleAssignment_2_1_4.eContents().get(0);
		private final RuleCall cRoleRoleIDTerminalRuleCall_2_1_4_0_1 = (RuleCall)cRoleRoleCrossReference_2_1_4_0.eContents().get(1);
		
		//ResourceAllocation:
		//	person=[Person|NameOrString] 'is' (factor=FactorAsPercentage 'in' course=[Course] | 'in' course=[Course] 'as'
		//	factor=FactorAsPercentage role=[Role]);
		@Override public ParserRule getRule() { return rule; }
		
		//person=[Person|NameOrString] 'is' (factor=FactorAsPercentage 'in' course=[Course] | 'in' course=[Course] 'as'
		//factor=FactorAsPercentage role=[Role])
		public Group getGroup() { return cGroup; }
		
		//person=[Person|NameOrString]
		public Assignment getPersonAssignment_0() { return cPersonAssignment_0; }
		
		//[Person|NameOrString]
		public CrossReference getPersonPersonCrossReference_0_0() { return cPersonPersonCrossReference_0_0; }
		
		//NameOrString
		public RuleCall getPersonPersonNameOrStringParserRuleCall_0_0_1() { return cPersonPersonNameOrStringParserRuleCall_0_0_1; }
		
		//'is'
		public Keyword getIsKeyword_1() { return cIsKeyword_1; }
		
		//factor=FactorAsPercentage 'in' course=[Course] | 'in' course=[Course] 'as' factor=FactorAsPercentage role=[Role]
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//factor=FactorAsPercentage 'in' course=[Course]
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//factor=FactorAsPercentage
		public Assignment getFactorAssignment_2_0_0() { return cFactorAssignment_2_0_0; }
		
		//FactorAsPercentage
		public RuleCall getFactorFactorAsPercentageParserRuleCall_2_0_0_0() { return cFactorFactorAsPercentageParserRuleCall_2_0_0_0; }
		
		//'in'
		public Keyword getInKeyword_2_0_1() { return cInKeyword_2_0_1; }
		
		//course=[Course]
		public Assignment getCourseAssignment_2_0_2() { return cCourseAssignment_2_0_2; }
		
		//[Course]
		public CrossReference getCourseCourseCrossReference_2_0_2_0() { return cCourseCourseCrossReference_2_0_2_0; }
		
		//ID
		public RuleCall getCourseCourseIDTerminalRuleCall_2_0_2_0_1() { return cCourseCourseIDTerminalRuleCall_2_0_2_0_1; }
		
		//'in' course=[Course] 'as' factor=FactorAsPercentage role=[Role]
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'in'
		public Keyword getInKeyword_2_1_0() { return cInKeyword_2_1_0; }
		
		//course=[Course]
		public Assignment getCourseAssignment_2_1_1() { return cCourseAssignment_2_1_1; }
		
		//[Course]
		public CrossReference getCourseCourseCrossReference_2_1_1_0() { return cCourseCourseCrossReference_2_1_1_0; }
		
		//ID
		public RuleCall getCourseCourseIDTerminalRuleCall_2_1_1_0_1() { return cCourseCourseIDTerminalRuleCall_2_1_1_0_1; }
		
		//'as'
		public Keyword getAsKeyword_2_1_2() { return cAsKeyword_2_1_2; }
		
		//factor=FactorAsPercentage
		public Assignment getFactorAssignment_2_1_3() { return cFactorAssignment_2_1_3; }
		
		//FactorAsPercentage
		public RuleCall getFactorFactorAsPercentageParserRuleCall_2_1_3_0() { return cFactorFactorAsPercentageParserRuleCall_2_1_3_0; }
		
		//role=[Role]
		public Assignment getRoleAssignment_2_1_4() { return cRoleAssignment_2_1_4; }
		
		//[Role]
		public CrossReference getRoleRoleCrossReference_2_1_4_0() { return cRoleRoleCrossReference_2_1_4_0; }
		
		//ID
		public RuleCall getRoleRoleIDTerminalRuleCall_2_1_4_0_1() { return cRoleRoleIDTerminalRuleCall_2_1_4_0_1; }
	}
	
	
	private final DepartmentElements pDepartment;
	private final NameOrStringElements pNameOrString;
	private final PersonElements pPerson;
	private final CourseElements pCourse;
	private final RoleElements pRole;
	private final FactorAsPercentageElements pFactorAsPercentage;
	private final ResourceAllocationElements pResourceAllocation;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public Rax2GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDepartment = new DepartmentElements();
		this.pNameOrString = new NameOrStringElements();
		this.pPerson = new PersonElements();
		this.pCourse = new CourseElements();
		this.pRole = new RoleElements();
		this.pFactorAsPercentage = new FactorAsPercentageElements();
		this.pResourceAllocation = new ResourceAllocationElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("tdt4250.ra.Rax2".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Department:
	//	shortName=ID '-' name=STRING
	//	'Persons:'
	//	staff+=Person*
	//	'Courses:'
	//	courses+=Course*
	//	'Allocations:'
	//	resourceAllocations+=ResourceAllocation*;
	public DepartmentElements getDepartmentAccess() {
		return pDepartment;
	}
	
	public ParserRule getDepartmentRule() {
		return getDepartmentAccess().getRule();
	}
	
	//NameOrString:
	//	ID | STRING;
	public NameOrStringElements getNameOrStringAccess() {
		return pNameOrString;
	}
	
	public ParserRule getNameOrStringRule() {
		return getNameOrStringAccess().getRule();
	}
	
	//Person:
	//	name=NameOrString;
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//Course:
	//	code=ID '-' name=NameOrString ('requires' roles+=Role (',' roles+=Role)*)?;
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}
	
	//Role:
	//	name=ID 'for' workload=FactorAsPercentage;
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//FactorAsPercentage ecore::EFloat:
	//	INT ('.' INT)? '%';
	public FactorAsPercentageElements getFactorAsPercentageAccess() {
		return pFactorAsPercentage;
	}
	
	public ParserRule getFactorAsPercentageRule() {
		return getFactorAsPercentageAccess().getRule();
	}
	
	//ResourceAllocation:
	//	person=[Person|NameOrString] 'is' (factor=FactorAsPercentage 'in' course=[Course] | 'in' course=[Course] 'as'
	//	factor=FactorAsPercentage role=[Role]);
	public ResourceAllocationElements getResourceAllocationAccess() {
		return pResourceAllocation;
	}
	
	public ParserRule getResourceAllocationRule() {
		return getResourceAllocationAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
