/**
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ide;

import tdt4250.ra.ide.AbstractRax1IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Rax1IdeModule extends AbstractRax1IdeModule {
}
