/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.tests

import com.google.inject.Inject
import org.eclipse.emf.ecore.util.EcoreUtil
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import tdt4250.ra.Department

@RunWith(XtextRunner)
@InjectWith(Rax2InjectorProvider)
class Rax2ParsingTest {
	@Inject
	ParseHelper<Department> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			IDI - "Dept. of CS"
			
			Persons:
				"Hallvard Trætteberg"
				Adrian
			
			Courses:
				TDT4250 - "Advanced Software Design" requires lecturer for 80%, exerciseTA for 20%
				IT1901 - InfProj requires lecturer for 60%, coordinator for 40%
				
			
			Allocations:
				"Hallvard Trætteberg" is 100% in TDT4250
				"Hallvard Trætteberg" is in IT1901 as 40% lecturer
				 Adrian is in IT1901 as 60% lecturer
				 Adrian is in IT1901 as 100% coordinator
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
		// the <=> 'spaceship' operator is mapped to Assert.assertEquals
		// when defining the operator_spaceship method below
		2 <=> result.staff.size()
		val hallvard = result.staff.get(0);
		val adrian = result.staff.get(1);
		2 <=> result.courses.size()
		val tdt4250 = result.courses.get(0);
		val it1901 = result.courses.get(1);
		2 <=> tdt4250.roles.size()
		2 <=> it1901.roles.size()
		
		4 <=> result.resourceAllocations.size()
		val hra1 = result.resourceAllocations.get(0)
		hallvard <=> hra1.person
		1.0f <=> hra1.workload
		null <=> hra1.role		
		val hra2 = result.resourceAllocations.get(1)
		hallvard <=> hra2.person
		0.4f <=> hra2.factor
		it1901.roles.get(0) <=> hra2.role		
		val ara1 = result.resourceAllocations.get(2)
		adrian <=> ara1.person
		0.6f <=> ara1.factor		
		it1901.roles.get(0) <=> ara1.role		
		val ara2 = result.resourceAllocations.get(3)
		adrian <=> ara2.person
		1.0f <=> ara2.factor		
		it1901.roles.get(1) <=> ara2.role		
	}
	
	// maps the <=> 'spaceship' operator to Assert.assertEquals
	private def void operator_spaceship(Object expected, Object actual) {
		Assert.assertEquals(expected, actual);
	}
}
