/**
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class Rax2DescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
