#include "asmdef.h"

DECLARE_GLOBAL(asm_function)


# ################################################################################
# name:           asm_function
# action:         Merge sort
# in:             An unsorted array
#
# out:            A sorted array
# modifies:       The input array
# notes:          Sorts the array in a specific way, the merge sort way
# ################################################################################
FUNC(asm_function):