/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import tdt4250.ra.ide.contentassist.antlr.internal.InternalRax2Parser;
import tdt4250.ra.services.Rax2GrammarAccess;

public class Rax2Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(Rax2GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, Rax2GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNameOrStringAccess().getAlternatives(), "rule__NameOrString__Alternatives");
			builder.put(grammarAccess.getResourceAllocationAccess().getAlternatives_2(), "rule__ResourceAllocation__Alternatives_2");
			builder.put(grammarAccess.getDepartmentAccess().getGroup(), "rule__Department__Group__0");
			builder.put(grammarAccess.getCourseAccess().getGroup(), "rule__Course__Group__0");
			builder.put(grammarAccess.getCourseAccess().getGroup_3(), "rule__Course__Group_3__0");
			builder.put(grammarAccess.getCourseAccess().getGroup_3_2(), "rule__Course__Group_3_2__0");
			builder.put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
			builder.put(grammarAccess.getFactorAsPercentageAccess().getGroup(), "rule__FactorAsPercentage__Group__0");
			builder.put(grammarAccess.getFactorAsPercentageAccess().getGroup_1(), "rule__FactorAsPercentage__Group_1__0");
			builder.put(grammarAccess.getResourceAllocationAccess().getGroup(), "rule__ResourceAllocation__Group__0");
			builder.put(grammarAccess.getResourceAllocationAccess().getGroup_2_0(), "rule__ResourceAllocation__Group_2_0__0");
			builder.put(grammarAccess.getResourceAllocationAccess().getGroup_2_1(), "rule__ResourceAllocation__Group_2_1__0");
			builder.put(grammarAccess.getDepartmentAccess().getShortNameAssignment_0(), "rule__Department__ShortNameAssignment_0");
			builder.put(grammarAccess.getDepartmentAccess().getNameAssignment_2(), "rule__Department__NameAssignment_2");
			builder.put(grammarAccess.getDepartmentAccess().getStaffAssignment_4(), "rule__Department__StaffAssignment_4");
			builder.put(grammarAccess.getDepartmentAccess().getCoursesAssignment_6(), "rule__Department__CoursesAssignment_6");
			builder.put(grammarAccess.getDepartmentAccess().getResourceAllocationsAssignment_8(), "rule__Department__ResourceAllocationsAssignment_8");
			builder.put(grammarAccess.getPersonAccess().getNameAssignment(), "rule__Person__NameAssignment");
			builder.put(grammarAccess.getCourseAccess().getCodeAssignment_0(), "rule__Course__CodeAssignment_0");
			builder.put(grammarAccess.getCourseAccess().getNameAssignment_2(), "rule__Course__NameAssignment_2");
			builder.put(grammarAccess.getCourseAccess().getRolesAssignment_3_1(), "rule__Course__RolesAssignment_3_1");
			builder.put(grammarAccess.getCourseAccess().getRolesAssignment_3_2_1(), "rule__Course__RolesAssignment_3_2_1");
			builder.put(grammarAccess.getRoleAccess().getNameAssignment_0(), "rule__Role__NameAssignment_0");
			builder.put(grammarAccess.getRoleAccess().getWorkloadAssignment_2(), "rule__Role__WorkloadAssignment_2");
			builder.put(grammarAccess.getResourceAllocationAccess().getPersonAssignment_0(), "rule__ResourceAllocation__PersonAssignment_0");
			builder.put(grammarAccess.getResourceAllocationAccess().getFactorAssignment_2_0_0(), "rule__ResourceAllocation__FactorAssignment_2_0_0");
			builder.put(grammarAccess.getResourceAllocationAccess().getCourseAssignment_2_0_2(), "rule__ResourceAllocation__CourseAssignment_2_0_2");
			builder.put(grammarAccess.getResourceAllocationAccess().getCourseAssignment_2_1_1(), "rule__ResourceAllocation__CourseAssignment_2_1_1");
			builder.put(grammarAccess.getResourceAllocationAccess().getFactorAssignment_2_1_3(), "rule__ResourceAllocation__FactorAssignment_2_1_3");
			builder.put(grammarAccess.getResourceAllocationAccess().getRoleAssignment_2_1_4(), "rule__ResourceAllocation__RoleAssignment_2_1_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private Rax2GrammarAccess grammarAccess;

	@Override
	protected InternalRax2Parser createParser() {
		InternalRax2Parser result = new InternalRax2Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Rax2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Rax2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
