/*
 * generated by Xtext 2.18.0.M3
 */
grammar InternalRax2;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package tdt4250.ra.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package tdt4250.ra.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import tdt4250.ra.services.Rax2GrammarAccess;

}

@parser::members {

 	private Rax2GrammarAccess grammarAccess;

    public InternalRax2Parser(TokenStream input, Rax2GrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Department";
   	}

   	@Override
   	protected Rax2GrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleDepartment
entryRuleDepartment returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDepartmentRule()); }
	iv_ruleDepartment=ruleDepartment
	{ $current=$iv_ruleDepartment.current; }
	EOF;

// Rule Department
ruleDepartment returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_shortName_0_0=RULE_ID
				{
					newLeafNode(lv_shortName_0_0, grammarAccess.getDepartmentAccess().getShortNameIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDepartmentRule());
					}
					setWithLastConsumed(
						$current,
						"shortName",
						lv_shortName_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_1='-'
		{
			newLeafNode(otherlv_1, grammarAccess.getDepartmentAccess().getHyphenMinusKeyword_1());
		}
		(
			(
				lv_name_2_0=RULE_STRING
				{
					newLeafNode(lv_name_2_0, grammarAccess.getDepartmentAccess().getNameSTRINGTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDepartmentRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_2_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_3='Persons:'
		{
			newLeafNode(otherlv_3, grammarAccess.getDepartmentAccess().getPersonsKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDepartmentAccess().getStaffPersonParserRuleCall_4_0());
				}
				lv_staff_4_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDepartmentRule());
					}
					add(
						$current,
						"staff",
						lv_staff_4_0,
						"tdt4250.ra.Rax2.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_5='Courses:'
		{
			newLeafNode(otherlv_5, grammarAccess.getDepartmentAccess().getCoursesKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDepartmentAccess().getCoursesCourseParserRuleCall_6_0());
				}
				lv_courses_6_0=ruleCourse
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDepartmentRule());
					}
					add(
						$current,
						"courses",
						lv_courses_6_0,
						"tdt4250.ra.Rax2.Course");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_7='Allocations:'
		{
			newLeafNode(otherlv_7, grammarAccess.getDepartmentAccess().getAllocationsKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDepartmentAccess().getResourceAllocationsResourceAllocationParserRuleCall_8_0());
				}
				lv_resourceAllocations_8_0=ruleResourceAllocation
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDepartmentRule());
					}
					add(
						$current,
						"resourceAllocations",
						lv_resourceAllocations_8_0,
						"tdt4250.ra.Rax2.ResourceAllocation");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRuleNameOrString
entryRuleNameOrString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getNameOrStringRule()); }
	iv_ruleNameOrString=ruleNameOrString
	{ $current=$iv_ruleNameOrString.current.getText(); }
	EOF;

// Rule NameOrString
ruleNameOrString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getNameOrStringAccess().getIDTerminalRuleCall_0());
		}
		    |
		this_STRING_1=RULE_STRING
		{
			$current.merge(this_STRING_1);
		}
		{
			newLeafNode(this_STRING_1, grammarAccess.getNameOrStringAccess().getSTRINGTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRulePerson
entryRulePerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonRule()); }
	iv_rulePerson=rulePerson
	{ $current=$iv_rulePerson.current; }
	EOF;

// Rule Person
rulePerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getPersonAccess().getNameNameOrStringParserRuleCall_0());
			}
			lv_name_0_0=ruleNameOrString
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getPersonRule());
				}
				set(
					$current,
					"name",
					lv_name_0_0,
					"tdt4250.ra.Rax2.NameOrString");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleCourse
entryRuleCourse returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCourseRule()); }
	iv_ruleCourse=ruleCourse
	{ $current=$iv_ruleCourse.current; }
	EOF;

// Rule Course
ruleCourse returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_code_0_0=RULE_ID
				{
					newLeafNode(lv_code_0_0, grammarAccess.getCourseAccess().getCodeIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCourseRule());
					}
					setWithLastConsumed(
						$current,
						"code",
						lv_code_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_1='-'
		{
			newLeafNode(otherlv_1, grammarAccess.getCourseAccess().getHyphenMinusKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getCourseAccess().getNameNameOrStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleNameOrString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCourseRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"tdt4250.ra.Rax2.NameOrString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_3='requires'
			{
				newLeafNode(otherlv_3, grammarAccess.getCourseAccess().getRequiresKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getCourseAccess().getRolesRoleParserRuleCall_3_1_0());
					}
					lv_roles_4_0=ruleRole
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getCourseRule());
						}
						add(
							$current,
							"roles",
							lv_roles_4_0,
							"tdt4250.ra.Rax2.Role");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_5=','
				{
					newLeafNode(otherlv_5, grammarAccess.getCourseAccess().getCommaKeyword_3_2_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getCourseAccess().getRolesRoleParserRuleCall_3_2_1_0());
						}
						lv_roles_6_0=ruleRole
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getCourseRule());
							}
							add(
								$current,
								"roles",
								lv_roles_6_0,
								"tdt4250.ra.Rax2.Role");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
	)
;

// Entry rule entryRuleRole
entryRuleRole returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRoleRule()); }
	iv_ruleRole=ruleRole
	{ $current=$iv_ruleRole.current; }
	EOF;

// Rule Role
ruleRole returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_name_0_0=RULE_ID
				{
					newLeafNode(lv_name_0_0, grammarAccess.getRoleAccess().getNameIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRoleRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_1='for'
		{
			newLeafNode(otherlv_1, grammarAccess.getRoleAccess().getForKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRoleAccess().getWorkloadFactorAsPercentageParserRuleCall_2_0());
				}
				lv_workload_2_0=ruleFactorAsPercentage
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRoleRule());
					}
					set(
						$current,
						"workload",
						lv_workload_2_0,
						"tdt4250.ra.Rax2.FactorAsPercentage");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleFactorAsPercentage
entryRuleFactorAsPercentage returns [String current=null]:
	{ newCompositeNode(grammarAccess.getFactorAsPercentageRule()); }
	iv_ruleFactorAsPercentage=ruleFactorAsPercentage
	{ $current=$iv_ruleFactorAsPercentage.current.getText(); }
	EOF;

// Rule FactorAsPercentage
ruleFactorAsPercentage returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_INT_0=RULE_INT
		{
			$current.merge(this_INT_0);
		}
		{
			newLeafNode(this_INT_0, grammarAccess.getFactorAsPercentageAccess().getINTTerminalRuleCall_0());
		}
		(
			kw='.'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getFactorAsPercentageAccess().getFullStopKeyword_1_0());
			}
			this_INT_2=RULE_INT
			{
				$current.merge(this_INT_2);
			}
			{
				newLeafNode(this_INT_2, grammarAccess.getFactorAsPercentageAccess().getINTTerminalRuleCall_1_1());
			}
		)?
		kw='%'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getFactorAsPercentageAccess().getPercentSignKeyword_2());
		}
	)
;

// Entry rule entryRuleResourceAllocation
entryRuleResourceAllocation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getResourceAllocationRule()); }
	iv_ruleResourceAllocation=ruleResourceAllocation
	{ $current=$iv_ruleResourceAllocation.current; }
	EOF;

// Rule ResourceAllocation
ruleResourceAllocation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getResourceAllocationRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getResourceAllocationAccess().getPersonPersonCrossReference_0_0());
				}
				ruleNameOrString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1='is'
		{
			newLeafNode(otherlv_1, grammarAccess.getResourceAllocationAccess().getIsKeyword_1());
		}
		(
			(
				(
					(
						{
							newCompositeNode(grammarAccess.getResourceAllocationAccess().getFactorFactorAsPercentageParserRuleCall_2_0_0_0());
						}
						lv_factor_2_0=ruleFactorAsPercentage
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getResourceAllocationRule());
							}
							set(
								$current,
								"factor",
								lv_factor_2_0,
								"tdt4250.ra.Rax2.FactorAsPercentage");
							afterParserOrEnumRuleCall();
						}
					)
				)
				otherlv_3='in'
				{
					newLeafNode(otherlv_3, grammarAccess.getResourceAllocationAccess().getInKeyword_2_0_1());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getResourceAllocationRule());
							}
						}
						otherlv_4=RULE_ID
						{
							newLeafNode(otherlv_4, grammarAccess.getResourceAllocationAccess().getCourseCourseCrossReference_2_0_2_0());
						}
					)
				)
			)
			    |
			(
				otherlv_5='in'
				{
					newLeafNode(otherlv_5, grammarAccess.getResourceAllocationAccess().getInKeyword_2_1_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getResourceAllocationRule());
							}
						}
						otherlv_6=RULE_ID
						{
							newLeafNode(otherlv_6, grammarAccess.getResourceAllocationAccess().getCourseCourseCrossReference_2_1_1_0());
						}
					)
				)
				otherlv_7='as'
				{
					newLeafNode(otherlv_7, grammarAccess.getResourceAllocationAccess().getAsKeyword_2_1_2());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getResourceAllocationAccess().getFactorFactorAsPercentageParserRuleCall_2_1_3_0());
						}
						lv_factor_8_0=ruleFactorAsPercentage
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getResourceAllocationRule());
							}
							set(
								$current,
								"factor",
								lv_factor_8_0,
								"tdt4250.ra.Rax2.FactorAsPercentage");
							afterParserOrEnumRuleCall();
						}
					)
				)
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getResourceAllocationRule());
							}
						}
						otherlv_9=RULE_ID
						{
							newLeafNode(otherlv_9, grammarAccess.getResourceAllocationAccess().getRoleRoleCrossReference_2_1_4_0());
						}
					)
				)
			)
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
