/**
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import tdt4250.ra.ui.AbstractRax2UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Rax2UiModule extends AbstractRax2UiModule {
  public Rax2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
