/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tdt4250.ra.xtext2.ui.internal.Xtext2Activator;

public class Rax2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Xtext2Activator.getInstance().getInjector("tdt4250.ra.Rax2");
	}

}
