/*
 * generated by Xtext 2.18.0.M3
 */
package tdt4250.ra.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tdt4250.ra.parser.antlr.internal.InternalRax2Parser;
import tdt4250.ra.services.Rax2GrammarAccess;

public class Rax2Parser extends AbstractAntlrParser {

	@Inject
	private Rax2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRax2Parser createParser(XtextTokenStream stream) {
		return new InternalRax2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Department";
	}

	public Rax2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Rax2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
